# Import library

In [17]:
from matplotlib import pyplot as plt
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Read data

In [18]:
# change file_data to where did you put it!
file_data = './glass.csv'
glass_df = pd.read_csv(file_data)
print(glass_df.info())
glass_types = glass_df['Type'].unique()
print(glass_types)
print(glass_df['Type'].value_counts())
X_1 = glass_df[glass_df.columns[:-1]]
y_1 = glass_df['Type']

X_train, X_test, y_train, y_test = train_test_split(X_1, y_1,test_size=0.25, random_state=42)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Id_Number  214 non-null    int64  
 1   RI         214 non-null    float64
 2   Na         214 non-null    float64
 3   Mg         214 non-null    float64
 4   Al         214 non-null    float64
 5   Si         214 non-null    float64
 6   K          214 non-null    float64
 7   Ca         214 non-null    float64
 8   Ba         214 non-null    float64
 9   Fe         214 non-null    float64
 10  Type       214 non-null    int64  
dtypes: float64(9), int64(2)
memory usage: 18.5 KB
None
[1 2 3 5 6 7]
2    76
1    70
7    29
3    17
5    13
6     9
Name: Type, dtype: int64


# Fitting model

In [22]:
# Call to Logistic Regression Model - sag: solving is based on Stochastic Average Gradient
lorg=LogisticRegression(multi_class='multinomial',solver='sag', max_iter=5000)
# and train model by Training Dataset
lorg.fit(X_train, y_train)
# Then Predict the Test data
Y_pred=lorg.predict(X_test)
Y_train_pred = lorg.predict(X_train)
# for accuracy
print("Accuracy score of test", accuracy_score(y_test,Y_pred))
print("Accuracy score of train", accuracy_score(y_train, Y_train_pred))
# for confusion matrix
cm=confusion_matrix(y_test,Y_pred)
print("Confuse matrix\n", cm)

Accuracy score of test 1.0
Accuracy score of train 0.99375
Confuse matrix
 [[14  0  0  0  0  0]
 [ 0 21  0  0  0  0]
 [ 0  0  4  0  0  0]
 [ 0  0  0  4  0  0]
 [ 0  0  0  0  3  0]
 [ 0  0  0  0  0  8]]
