# Import library

In [38]:
from pandas import *
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# Read data

In [39]:
df = read_csv("framingham.csv")
df.head()
df.isnull().sum()
df=df.dropna(how="any", axis=0)
df = np.asarray(df.T)
X = df[:-1].T
y = df[-1].T

print(X.shape)
print(y.shape)

(3656, 15)
(3656,)


# Split to train and validation

In [40]:

x_train, x_validation, y_train, y_validation = train_test_split(X, y, test_size=0.3, random_state=100)
print(x_train)
print(y_train)

[[  0.    42.     1.   ...  23.43  95.    85.  ]
 [  0.    45.     4.   ...  21.25  60.    60.  ]
 [  1.    44.     3.   ...  28.92  73.    72.  ]
 ...
 [  1.    49.     1.   ...  27.92  75.    74.  ]
 [  0.    41.     1.   ...  25.54  75.    58.  ]
 [  0.    46.     2.   ...  26.67  80.   102.  ]]
[0. 0. 1. ... 1. 0. 0.]


# Fitting model perception

In [41]:
clf = Perceptron(tol=1e-3, random_state=0)
clf.fit(x_train, y_train)


Perceptron()

# Predict validation and show score

In [42]:
y_pre = clf.predict(x_validation)
print("Validation predict: \n", y_pre)
print("accuracy score:", accuracy_score(y_pre, y_validation))
print("precision score:", precision_score(y_pre, y_validation))
print("recalll score:", recall_score(y_pre, y_validation))

Validation predict: 
 [0. 0. 0. ... 1. 0. 0.]
accuracy score: 0.7575205104831358
precision score: 0.38285714285714284
recalll score: 0.29777777777777775


# Fitting model with logistic regression

In [43]:
logr = LogisticRegression(penalty="none")
logr.fit(x_train, y_train)

C:\Users\LENOVO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(penalty='none')

# Predict validation with logistic regression

In [44]:
y_pre = logr.predict(x_validation)
print("Validation predict: \n", y_pre)
print("accuracy score:", accuracy_score(y_pre, y_validation))
print("precision score:", precision_score(y_pre, y_validation))
print("recalll score:", recall_score(y_pre, y_validation))

Validation predict: 
 [0. 0. 0. ... 0. 0. 0.]
accuracy score: 0.845031905195989
precision score: 0.05142857142857143
recalll score: 0.6923076923076923
